Traceback (most recent call last):
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3022, in _dep_map
    return self.__dep_map
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2816, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geez219/anaconda3/envs/tf2.1/bin/fastestimator", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    @_call_aside
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3236, in _call_aside
    f(*args, **kwargs)
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3265, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 795, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2737, in requires
    dm = self._dep_map
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3024, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3041, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3038, in reqs_for_extra
    if not req.marker or req.marker.evaluate({'extra': extra}):
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/markers.py", line 297, in evaluate
    current_environment = default_environment()
  File "/home/geez219/anaconda3/envs/tf2.1/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/markers.py", line 261, in default_environment
    "platform_machine": platform.machine(),
KeyboardInterrupt
